server:
  port: 9527

spring:
  application:
    name: shop-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: shopspringcloud-dept
    mydept.path: /mydept/**
  ignored-services: shopspringcloud-dept
  prefix: /pagoda


info:
  app.name: pagoda-springcloud
  company.name: www.pagoda.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$